replicaCount: 2

image:
  repository: 437670317020.dkr.ecr.eu-north-1.amazonaws.com/final-project-ecr
  tag: v1.0.6
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  host: django.example.com
  path: /
  pathType: Prefix
  tls: false

config:
  DJANGO_SETTINGS_MODULE: goit.settings
  DEBUG: "False"
  SECRET_KEY: replace-me
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
