pipeline {
  agent {
    kubernetes {
      yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.23.2-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
    - name: git
      image: alpine/git:2.45.2
      command:
        - sleep
      args:
        - 99d
'''
    }
  }

  environment {
    AWS_REGION       = 'eu-north-1'
    ECR_REGISTRY     = '437670317020.dkr.ecr.eu-north-1.amazonaws.com'
    IMAGE_NAME       = 'final-project-ecr'
    IMAGE_TAG        = "v1.0.${BUILD_NUMBER}"
    GITOPS_REPOSITORY = 'https://github.com/DimaKisiv/devops.git'
    GITOPS_BRANCH    = 'final-project'
    COMMIT_EMAIL     = 'jenkins@localhost'
    COMMIT_NAME      = 'jenkins'
  }

  stages {
    stage('Checkout Source') {
      steps {
        container('git') {
          checkout scm
        }
      }
    }

    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context "${WORKSPACE}/final-project/django" \
              --dockerfile "${WORKSPACE}/final-project/django/Dockerfile" \
              --destination="${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}" \
              --cache=true
          '''
        }
      }
    }

    stage('Update Helm Chart Tag') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh '''
              rm -rf gitops-repo
              REPO_URL="${GITOPS_REPOSITORY#https://}"
              git clone "https://${GIT_USERNAME}:${GIT_PAT}@${REPO_URL}" gitops-repo
              cd gitops-repo

              git checkout "${GITOPS_BRANCH}"
              sed -i "s|^  tag: .*|  tag: ${IMAGE_TAG}|" final-project/charts/django-app/values.yaml

              git config user.email "${COMMIT_EMAIL}"
              git config user.name "${COMMIT_NAME}"

              if git diff --quiet final-project/charts/django-app/values.yaml; then
                echo "Helm values already use image tag ${IMAGE_TAG}"
                exit 0
              fi

              git add final-project/charts/django-app/values.yaml
              git commit -m "chore: update image tag to ${IMAGE_TAG} [skip ci]"
              git push origin "${GITOPS_BRANCH}"
            '''
          }
        }
      }
    }
  }
}