{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .repo_url | quote }}
    targetRevision: {{ .target_revision | quote }}
    path: {{ .path | quote }}
  destination:
    server: {{ .destination_server | quote }}
    namespace: {{ .namespace | quote }}
  syncPolicy:
    {{- if .automated }}
    automated:
      prune: {{ .prune }}
      selfHeal: {{ .self_heal }}
    {{- end }}
    syncOptions:
      - CreateNamespace={{ .create_namespace }}
---
{{- end }}