apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-service
  labels:
    app: {{ .Release.Name }}-django-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-django-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}