replicaCount: 2

image:
  repository: 123456789012.dkr.ecr.eu-north-1.amazonaws.com/lesson-8-9-ecr
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DJANGO_SETTINGS_MODULE: goit.settings
  DEBUG: "False"
  SECRET_KEY: replace-me
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_PASSWORD: change_me
  POSTGRES_DB: django_db

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
