configs:
  params:
    server.insecure: true

server:
  service:
    type: LoadBalancer

  extraArgs:
    - --insecure

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

redis:
  enabled: true

crds:
  install: true
