server:
  service:
    type: LoadBalancer
    servicePortHttps: 443

applications:
  - name: ${app_name}
    namespace: ${app_namespace}
    project: default
    source:
      repoURL: ${repo_url}
      path: ${app_path}
      targetRevision: ${repo_target_revision}
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: ${app_namespace}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: ${app_name}
    url: ${repo_url}
    username: ${repo_username}
    password: ${repo_password}

repoConfig:
  insecure: "false"
  enableLfs: "true"
